version: "3"
services:
  server:
    build: .
    command: npm start
    volumes:
      - ./server:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - redis
      - mongo
  scheduler:
    build: .
    command: npm start
    volumes:
      - ./scheduler:/usr/src/app
    depends_on:
      - redis
      - mailer
  mailer:
    build: .
    command: npm start
    volumes:
      - ./mailer:/usr/src/app
    depends_on:
      - redis
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
  redis:
    image: redis:6.0-alpine
    ports:
      - "6379:6379"
