name: Node.js CI

on: [push]

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: actions/setup-node@v1
        with:
          node-version: "14.4.0"
      # - run: npm install
      - run: npm test
        working-directory: ./server

  scheduler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: actions/setup-node@v1
        with:
          node-version: "14.4.0"
      # - run: npm install
      - run: npm test
        working-directory: ./scheduler
