name: Node.js CI

on: [push]

jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: actions/setup-node@v1
        with:
          node-version: "14.4.0"
      - run: |
          cd server
          npm install
          npm test
        env:
          AUTH_KEY: ${{ secrets.AUTH_KEY }}

  scheduler:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: actions/setup-node@v1
        with:
          node-version: "14.4.0"
      - run: |
          cd scheduler
          npm install
          npm test

  mailer:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: actions/setup-node@v1
        with:
          node-version: "14.4.0"
      - run: |
          cd mailer
          npm install
          npm test
